Actualizacion sueldo
LogiLinkP/praxus-node-backend pull request #89
Opened 2023-10-12 21:21 UTC by Balbont

PROBAR CON FRONT id_practica_respuesta_ramos. Se actualizan los ramos de todo. Para probar, primero modificar los cron de actualización de sueldo  (ahora se ejecutan a las 00:00). Luego, inscribir una practica con un alumno y finalizarla marcando algunos ramos como útiles en la encuesta final. Cuando se ejecute el cron, en la vista de estadísticas remuneración (del encargado), se debe actualizar el sueldo del tipo de practica elegido, la carrera del alumno, la empresa y los ramos seleccionados.

2023-10-14 02:58 UTC, Balbont commented
Front requerido ya esta pusheado a dev

2023-10-21 01:24 UTC, Lirlisa requested changes

2023-10-21 01:24 UTC, Lirlisa commented on scheduler/carrera/index.ts
> +            if (practica_asociada.sueldo != null){
Me da este error cuando se ejecuta el cron:
TypeError: Cannot read properties of null (reading 'sueldo')

ese error es debido a que practica asociada es null

2023-10-21 21:36 UTC, Lirlisa approved these changes

2023-10-21 21:36 UTC, merged